version: '2.0'
services:
  nginx:
    image: nginx
    ports:
    - "8080:80"
    volumes:
    - "/home/pi/server/src/client/build/:/usr/share/nginx/html:ro"
    - "/home/pi/server/src/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
  python:
    build: /home/pi/server/src/server/
    